Nueva Preferencia: Sprite Resize
Foxterosa/BoH-Bay pull request #161
Opened 2020-07-27 01:23 UTC by FunnyYellowDoge

Añade una nueva preferencia en el Character Setup con la cual puedes cambiarle el tamaño a tu personaje dependiendo de su altura, sin necesidad de hacerlo Genemodder.

Aplica para todas las razas.

De paso, elimina las traits de este tipo.

2020-07-27 16:01 UTC, Evankhell561 commented
Danita, podrias quitar esto.
![image](https://user-images.githubusercontent.com/49106866/88564153-dc21c700-d000-11ea-8bfd-ce2160885f1d.png)
dejalo activado por defecto. Y en cambio pones un valor para la altura normal.

2020-07-27 16:05 UTC, Evankhell561 requested changes

2020-07-27 16:05 UTC, Evankhell561 commented on code/modules/mob/living/carbon/human/descriptors/mob_resize.dm
> +/mob/living/carbon/human/update_body()
añadir esto al update body aumentaré el numero de procesos en gran cantidad. Lo mejor sera que el sprite_resize cambie el size_multiplier al aplicar las preferencias al cuerpo del jugador.

2020-07-27 16:09 UTC, Evankhell561 requested changes

2020-07-27 16:09 UTC, Evankhell561 commented on code/modules/mob/living/carbon/human/descriptors/mob_resize.dm
> +	character.sprite_resize = sprite_resize
por ejemplo acá. puedes poner 
```
if(sprite_resize)
		switch(character.descriptors["height"])
			if(1)
				character..size_multiplier = 0.80
			if(2)
				character..size_multiplier = 0.90
			if(4)
				character..size_multiplier = 1.10
			if(5)
				character..size_multiplier = 1.20
```

2020-07-27 16:15 UTC, Evankhell561 requested changes

2020-07-27 16:15 UTC, Evankhell561 commented on code/modules/client/preference_setup/general/02_body.dm
> +	. += pref.sprite_resize ? "<b>Yes.</b>" : "No."
si pones `"<b>... </b>"` para el yes, creo que tambien deberias ponerlo para el no. O no lo pongas para ninguno.

2020-07-27 16:18 UTC, Evankhell561 requested changes

2020-07-27 16:18 UTC, Evankhell561 commented on code/modules/mob/living/carbon/human/descriptors/mob_resize.dm
> +	var/sprite_resize
siguiendo los cambios que te dije, creo que esta variable es inecesaria.

2020-07-28 11:48 UTC, Evankhell561 commented on code/modules/client/preference_setup/general/02_body.dm
> +/datum/preferences/copy_to(mob/living/carbon/human/character, is_preview_copy = FALSE)
Funcionó, Danita?

2020-07-28 11:54 UTC, Evankhell561 commented on code/modules/client/preference_setup/general/02_body.dm
> +/datum/preferences/copy_to(mob/living/carbon/human/character, is_preview_copy = FALSE)
También. ya que estas modificando archivos del repo original podrias meter este code en su respectivo proc, al final del copy_to que ya está en el repo.

2020-07-28 17:31 UTC, FunnyYellowDoge commented on code/modules/client/preference_setup/general/02_body.dm
> +/datum/preferences/copy_to(mob/living/carbon/human/character, is_preview_copy = FALSE)
See, funcionó. Y prefiero dejarlo todo en un archivo, ya que es un proc en específico.

2020-07-28 20:00 UTC, merged

2020-08-02 12:01 UTC, Evankhell561 commented on code/modules/client/preference_setup/general/02_body.dm
> +/datum/preferences/copy_to(mob/living/carbon/human/character, is_preview_copy = FALSE)
como veas, solo que si van a modificar el repo original, modificar pros remotamente promueve el codigo espagueti. No lo digo por este pr en especifico sino por si se usa como precedente para seguir haciendo lo mismo.