Tradunoth (WIP)
Foxterosa/BoH-Bay pull request #89
Opened 2020-06-27 22:16 UTC by N0thy

Just... U know, right?
![e9790f86668f45f83c62f8e165f244c3](https://user-images.githubusercontent.com/53350410/85933182-8c05f680-b8d4-11ea-8e44-dc9c1669b722.gif)
![79774a28567c6e503edb4aff45e70bce](https://user-images.githubusercontent.com/53350410/85933181-8ad4c980-b8d4-11ea-82eb-f09a8665921a.gif)
![original](https://user-images.githubusercontent.com/53350410/85933183-8dcfba00-b8d4-11ea-8668-733d52518e9d.gif)

2020-07-01 22:13 UTC, N0thy commented
![tenor (1)](https://user-images.githubusercontent.com/53350410/86296306-ca632480-bbf8-11ea-8fd8-f01c0115c5ad.gif)
Senko para quien vea esto uwu

2020-07-01 22:14 UTC, Evankhell561 commented
> ![tenor (1)](https://user-images.githubusercontent.com/53350410/86296306-ca632480-bbf8-11ea-8fd8-f01c0115c5ad.gif)
> Senko para quien vea esto uwu

vaya dale senko a su abuela

2020-07-01 22:20 UTC, N0thy commented
No tengo abuela a quien darle senkos.

2020-07-01 22:21 UTC, Evankhell561 requested changes

2020-07-01 22:21 UTC, Evankhell561 commented on code/modules/mob/living/carbon/human/human_attackhand.dm
> +			visible_message("<span class='danger'>[H] ha golpeado a [src]!</span>")
ha golpeado a [src.name]

2020-07-01 22:21 UTC, Evankhell561 commented on code/modules/mob/living/carbon/human/human_attackhand.dm
> +				visible_message("<span class='danger'>[H] ha debilitado a [src]!</span>")
src.name

2020-07-01 22:21 UTC, Evankhell561 commented on code/modules/mob/living/carbon/human/human_attackhand.dm
> +				H.visible_message("<span class='notice'>[H] realiza CPR en [src]!</span>")
src.name

2020-07-31 16:38 UTC, N0thy commented on code/modules/mob/living/carbon/human/human_attackhand.dm
> +			visible_message("<span class='danger'>[H] ha golpeado a [src]!</span>")
corregido.

2020-08-04 13:22 UTC, closed without merging